<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Block_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get st_store by id
     */
    function get_st_store($id)
    {
        $st_store = $this->db->query("
            SELECT
                *

            FROM
                `st_blocks`

            WHERE
                `id` = id
        ",array($id))->row_array();

        return $st_store;
    }

    public function read_box($id) {
        $this->db->where('id', $id);
        $query = $this->db->get('st_blocks');
        if ($query->num_rows() > 0) {
            $data = $query->row();
            return $data;
        }
        return FALSE;
    }
    
    /*
     * Get all st_stores
     */
    function get_all_st_stores()
    {
        $st_stores = $this->db->query("
            SELECT
                *

            FROM
                `st_blocks`

            WHERE
                1 = 1
        ")->result_array();

        return $st_stores;

        
    }
    
    /*
     * function to add new st_store
     */
    function add_st_store($params)
    {
        $this->db->insert('st_blocks',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update st_store
     */
    function update_st_store($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('st_blocks',$params);
        if($response)
        {
            return "st_store updated successfully";
        }
        else
        {
            return "Error occuring while updating st_store";
        }
    }
    
    /*
     * function to delete st_store
     */
    function delete_st_store($id)
    {
        $response = $this->db->delete('st_blocks',array('id'=>$id));
        if($response)
        {
            return "st_store deleted successfully";
        }
        else
        {
            return "Error occuring while deleting st_store";
        }
    }
}
